name: Build (With Tests)

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Run tests and build
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      # Cache
      - uses: actions/cache@v3
        with:
          path: ./Library
          key: Library-${{ hashFiles('./Assets/**', './Packages/**', './ProjectSettings/**') }}
          restore-keys: |
            Library-

      # Test
      - name: Unity - Test runner
        uses: game-ci/unity-test-runner@v4.1.1
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: ./
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          unityVersion: 2023.2.5f1
          testMode: playmode

      # Build
      - name: Build project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: WebGL
          projectPath: ./
          unityVersion: 2023.2.5f1
          allowDirtyBuild: true
          buildName: LatestBuild

      # Deploy
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/WebGL/LatestBuild
          publish_branch: webGL

      # Output
      - name: Upload build to artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Build
          path: ./build/WebGL/LatestBuild
