name: Unity Test

on:
  workflow_dispatch:
    inputs:
      run-tests:
        description: "Run Unity tests"
        default: "true"

jobs:
  test:
    name: Run Unity tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Define environment variables for Unity license
      - name: Set up Unity license
        run: echo "${{ secrets.UNITY_LICENSE }}" > Unity.alf

      # Run Unity tests
      - name: Run Unity tests
        uses: game-ci/unity-test-runner@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: ./
          githubToken: ${{ secrets.GITHUB_TOKEN }}

      # Upload test results as artifacts
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: TestResults
          path: ./Artifacts
